from pathlib import Path

from openpyxl import load_workbook

from openlca_agent.models import CalculationRun, ImpactResult, ProductModel
from openlca_agent.reporting import export_result, generate_compliance_report


def _run() -> CalculationRun:
    return CalculationRun(
        run_id="run-test",
        product_system={"id": "ps1", "name": "Bottle system"},
        impact_method={"id": "m1", "name": "EF 3.1"},
        total_impacts=[
            ImpactResult(
                impact_category="Climate change",
                value=1.23,
                unit="kg CO2 eq",
            )
        ],
        hotspots=[],
        assumptions=["Foreground model generated by AI workflow."],
        missing_data=["Supplier electricity mix"],
    )


def test_export_result_writes_expected_excel_sheets(tmp_path: Path) -> None:
    path = export_result(_run(), output_dir=tmp_path, formats=["xlsx"])["xlsx"]

    workbook = load_workbook(path)

    assert {"META_INFO", "TOTAL_IMPACTS", "HOTSPOTS", "ASSUMPTIONS", "MISSING_DATA"}.issubset(
        set(workbook.sheetnames)
    )
    assert workbook["TOTAL_IMPACTS"]["A1"].value == "IMPACT_CATEGORY_NAME"


def test_generate_compliance_report_contains_review_warning_and_sections(tmp_path: Path) -> None:
    model = ProductModel(product_name="Bottle", functional_unit="1 piece")

    report = generate_compliance_report(
        run=_run(),
        product_model=model,
        output_dir=tmp_path,
        standards=["PCF", "EPD", "CBAM", "DPP"],
    )

    text = Path(report.files["markdown"]).read_text(encoding="utf-8")
    assert "draft / for review" in text
    assert "Process Mapping" in text
    assert "PCF" in text
    assert report.files["excel"].endswith("results.xlsx")
